config/routes.rb
Rails.application.routes.draw do

  root "categories#index"

  devise_for :users
  
  resources :categories, shallow: true do 
    resources :tasks
  end

  get '/today' => 'tasks#today', as: :tasks_today

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    belongs_to :user
    has_many :tasks, :dependent => :delete_all 
    
    validates :name, 
        presence:true
        
    validates :description, 
        presence:true, 
        length: {
            minimum: 3,
            maximum: 280
            }

    validates :color,
        presence: true,
        format: { with: /\A#(?:[0-9a-fA-F]{3}){1,2}\z/ }
        
end

app/models/task.rb
class Task < ApplicationRecord
    belongs_to :category

    validates :name, 
        presence:true

    validates :due_date,
        presence:true

    scope :tasks_today, -> { where("due_date = ?", Date.today) }
    
    # task description not required
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :categories, :dependent => :delete_all 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    add_flash_types :info, :error, :warning
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

    before_action :authenticate_user!
    
    def index
        @categories = current_user.categories.all
    end
    
    def show
        @category = Category.find(params[:id])
    end
    
    def new
        @category = current_user.categories.build
    end
    
    def create
        @category = current_user.categories.build(category_params)

        if @category.save
            redirect_to categories_path, notice: "New category created"
        else
            render :new
        end
    end

    def edit
        @category = Category.find(params[:id])
    end

    def update 
        @category = Category.find(params[:id])

        if @category.update(category_params)
          redirect_to category_path(@category), notice: "Category updated"
        else
          render :edit
        end
    end

    def destroy
        @category = Category.find(params[:id])
        @category.destroy
    
        redirect_to categories_path, notice: "Category deleted"
    end

    private
    def category_params
        params.require(:category).permit(:name, :description, :color)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

    before_action :authenticate_user!
    before_action :get_category, only: [:index, :new, :create]
    before_action :get_categories, only: :today

    def index
        @tasks = @category.tasks
    end

    def today
        @tasks = Task.tasks_today
    end
        
    def show
        @task = Task.find(params[:id])
    end

    def new
        @task = @category.tasks.build
    end
    
    def create
        @task = @category.tasks.build(task_params)
        @task.user_id = current_user.id
        @task.category_id = @category.id

        if @task.save
            redirect_to category_path(@category), notice: "New task created"
        else
            render :new
        end
    end

    def edit
        @task = Task.find(params[:id])
    end
    
    def update 
        @task = Task.find(params[:id])

        if @task.update(task_params)
          redirect_to task_path, notice: "Task updated"
        else
          render :edit
        end
    end  

    def destroy
        @task = Task.find(params[:id])
        @task.destroy
    
        redirect_to task_path, notice: "Task deleted"
    end

    private
    def get_category
        @category = current_user.categories.find(params[:category_id])
    end

    def get_categories
        @categories = current_user.categories.all
    end

    def task_params
        params.require(:task).permit(:name, :due_date, :description, :category_id, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/categories/_form.html.erb
<%= form_with model: @category, local: true do |f| %>

    <div class="errors-container">
        <p>
            <% if @category.errors.any? %>
                <ul>    
                    <% @category.errors.full_messages.each do |message| %>
                        <li> <%= message %> </li>
                    <% end %>
                </ul>
            <% end %>
        </p>
    </div>

    <p>
        <label>Category</label><br>
        <%= f.text_field :name, :placeholder => "Self-Care" %>
    </p>

    <p>
        <label>Color</label><br>
        <div class="color-picker" data-controller="color-picker">
            <%= f.text_field :color, data: { target: "color-picker.input" }, :cols => 45 %>
            <div data-target="color-picker.picker"></div>
        </div>
    </p>

    <p>
        <label>Description</label><br>
        <%= f.text_area :description, :cols => 50, :rows => 5, :placeholder => "Because you cannot pour from an empty cup" %>
    </p>

    <p>
        <%= f.submit class: "button button-solid" %>
    </p>

<% end %>

app/views/categories/edit.html.erb
<div class="title-area">
    <h1>Edit Category</h1>
</div>

<div class="container">
    <%= render "form", category: @category %>
</div>

app/views/categories/index.html.erb
<div class="title-area">
    <h1>Categories</h1>
</div>

<div class="container">
    <% @categories.each do |category| %>
        <div class="category" style="box-shadow: 10px 10px 0 0 <%= category.color %>;">
            <div class="category-text">
                <h5><%= link_to category.name, category %></h5>
            </div>
            <%= link_to '<i class="lni lni-checkbox"></i>&emsp;Add Task'.html_safe, new_category_task_path(category) %>
        </div>
    <% end %>
</div>

app/views/categories/new.html.erb
<div class="title-area">
    <h1>Create a Category</h1>
</div>

<div class="container">
    <%= render "form", category: @category %>
</div>

app/views/categories/show.html.erb
<div class="title-area">
    <h1 style="box-shadow: inset 0 -18px 0 <%= @category.color %>" ><%= @category.name %></h1>
</div>

<div class="container">
    <div class="category-description">
    <p class="big"><%= @category.description %></p>
    </div>
</div>
<div class="buttons-container">
    <%= link_to '<i class="lni lni-checkbox"></i>&emsp;Add Task'.html_safe, new_category_task_path(@category), class: "button button-solid" %>
    <%= link_to '<i class="lni lni-pencil-alt"></i>&emsp;Edit'.html_safe, edit_category_path(@category), class: "button button-outline" %>
    <%= link_to '<i class="lni lni-trash"></i>&emsp;Delete'.html_safe, @category,
        class: "button button-outline",
        method: :delete,
        data: { confirm: "Are you sure you want to delete this category? This action cannot be reversed." } %>
</div>

<div class="container">
    <% @category.tasks.each do |task| %>
        <div class="task" style="box-shadow: 10px 10px 0 0 <%= @category.color %>;">
            <div class="task-text">
                <h3><%= link_to task.name, task %></h3>
                <p class="small">Category: <%= @category.name %>&emsp;|&emsp;Due: <%= task.due_date.to_formatted_s(:long) %></p>
            </div>
            <%= link_to '<i class="lni lni-eye"></i>&emsp;View'.html_safe, task_path(task) %>
            <%= link_to '<i class="lni lni-pencil-alt"></i>&emsp;Edit'.html_safe, edit_task_path(task) %>
            <%= link_to '<i class="lni lni-trash"></i>&emsp;Delete'.html_safe, task,
                method: :delete,
                data: { confirm: "Are you sure you want to delete this task? This action cannot be reversed." } %>
        </div>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDoIt</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= favicon_link_tag asset_path('favicon.png') %>
    <link href="https://cdn.lineicons.com/2.0/LineIcons.css" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Epilogue:wght@300;400;600;700&display=swap" rel="stylesheet">
  </head>

  <body>
    <%= render "shared/sidebar" %>
    <div class="main">
      <%= render "shared/flash" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_flash.html.erb
<% flash.each do |type, msg| %>
    <div class="flash-container">
        <p><%= msg %></p>
    </div>
<% end %>

app/views/shared/_sidebar.html.erb
<div id="sidebar">

    <div id="sidebar-container">

        <a href="/">
            <div class="logo-container">
                <%= image_tag ("logo.png"), id: "logo-img" %>
                <h5>ToDoIt</h5>
            </div>
        </a>

        <% if user_signed_in? %>

            <div class="nav-container">
                <nav>
                    <ul>
                    <li><%= link_to 'Tasks Due Today', tasks_today_path, class: "low-contrast" %></li>
                    <li><%= link_to 'All Categories', categories_path, class: "low-contrast" %></li>
                    </ul>
                </nav>
            </div>

            <div class="sidebar-buttons-container">
                <%= link_to '<i class="lni lni-tag"></i>&emsp;Create Category'.html_safe, new_category_path, class: "button button-outline" %>
                <%= link_to '<i class="lni lni-user"></i>&emsp;Sign Out'.html_safe, destroy_user_session_path, :method => :delete, class: "button button-solid" %>
            </div>

            <p class="footer-text low-contrast">Crafted with <i class="lni lni-heart-filled"></i> using Ruby on Rails.</p>
    
        <% else %>
        <% end %>

    </div>

</div>

app/views/tasks/_form.html.erb
<%= form_with model: @task, url: category_tasks_path, local: true do |f| %>

    <div class="errors-container">
        <p>
            <% if @task.errors.any? %>
                <ul>    
                    <% @task.errors.full_messages.each do |message| %>
                        <li> <%= message %> </li>
                    <% end %>
                </ul>
            <% end %>
        </p>
    </div>

    <p>
        <label>Task</label><br>
        <%= f.text_field :name, :placeholder => "Eat apple" %>
    </p>

    <p>
        <label>Due Date</label><br>
          <%= f.text_field :due_date,
                    data: {
                      controller: "flatpickr",
                      flatpickr_min_date: Date.today }
            %>
    </p>

    <p>
        <label>Notes (optional)</label><br>
        <%= f.text_area :description, :cols => 50, :rows => 5, :placeholder => "An apple a day keeps the doctor away" %>
    </p>

    <p>
        <%= f.submit class: "button button-solid" %>
    </p>

<% end %>

app/views/tasks/edit.html.erb
<div class="title-area">
    <h1>Edit Task</h1>
</div>

<div class="container">
    <%= form_with model: @task, local: true do |f| %>

    <div class="errors-container">
        <p>
            <% if @task.errors.any? %>
                <ul>    
                    <% @task.errors.full_messages.each do |message| %>
                        <li> <%= message %> </li>
                    <% end %>
                </ul>
            <% end %>
        </p>
    </div>

    <p>
        <label>Task</label><br>
        <%= f.text_field :name, :placeholder => "Eat apple" %>
    </p>

    <p>
        <label>Due Date</label><br>
          <%= f.text_field :due_date,
                    data: {
                      controller: "flatpickr",
                      flatpickr_min_date: Date.today }
            %>
    </p>

    <p>
        <label>Notes (optional)</label><br>
        <%= f.text_area :description, :cols => 50, :rows => 5, :placeholder => "An apple a day keeps the doctor away" %>
    </p>

    <p>
        <%= f.submit class: "button button-solid" %>
    </p>

<% end %>
</div>

app/views/tasks/index.html.erb
<div class="title-area">
    <h1>Tasks</h1>
</div>

<div class="container">
    <% @tasks.each do |task| %>
        <div class="category">
            <div class="category-text">
                <h3><%= link_to task.name, task %></h3>
                <p><%= truncate( task.description, length: 60, omission: '...' ) %></p>
                <p class="small"><%= time_ago_in_words(task.created_at) %> ago</p>
            </div>
            <a href="/tasks/<%= task.id %>"><i class="lni lni-eye"></i>&emsp;View</a>
            <a href="/tasks/<%= task.id %>/edit"><i class="lni lni-pencil-alt"></i>&emsp;Edit</a>
            <%= link_to '<i class="lni lni-trash"></i>&emsp;Delete'.html_safe, task,
                method: :delete,
                data: { confirm: "Are you sure you want to delete this task? This action cannot be reversed." } %>
        </div>
    <% end %>
</div>

app/views/tasks/new.html.erb
<div class="title-area">
    <h1>Create a Task</h1>
</div>

<div class="container">
    <%= render "form", task: @task %>
</div>

app/views/tasks/show.html.erb
<div class="title-area">
    <h1><%= @task.name %></h1>
</div>

<div class="container">
    <div class="task-description">
    <p class="big"><%= @task.description %></p>
    <p class="low-contrast">Due: <%= @task.due_date.to_formatted_s(:long) %></p>
    </div>
</div>
<div class="buttons-container">
    <%= link_to '<i class="lni lni-pencil-alt"></i>&emsp;Edit'.html_safe, edit_task_path(@task), class: "button button-solid" %>
    <%= link_to '<i class="lni lni-trash"></i>&emsp;Delete'.html_safe, @task,
        class: "button button-outline",
        method: :delete,
        data: { confirm: "Are you sure you want to delete this task? This action cannot be reversed." } %>
</div>

app/views/tasks/today.html.erb
<div class="title-area">
    <h1>Your Tasks Due Today</h1>
</div>

<div class="container" >
    <% @tasks.each do |task| %>
        <div class="task" style="box-shadow: 10px 10px 0 0 <%= task.category.color %>;">
            <div class="task-text">
                <h3><%= link_to task.name, task %></h3>
                <p class="small">Category: <%= task.category.name %>&emsp;|&emsp;Due: <%= task.due_date.to_formatted_s(:long) %></p>
            </div>
            <%= link_to '<i class="lni lni-eye"></i>&emsp;View'.html_safe, task_path(task) %>
            <%= link_to '<i class="lni lni-pencil-alt"></i>&emsp;Edit'.html_safe, edit_task_path(task) %>
            <%= link_to '<i class="lni lni-trash"></i>&emsp;Delete'.html_safe, task,
                method: :delete,
                data: { confirm: "Are you sure you want to delete this task? This action cannot be reversed." } %>
        </div>
    <% end %>
</div>